# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08c7dec38f66dd4dc843974dc33df22cf2f2b5d13561d81c5250b621e7acd7379601263aad7aebafe7c4525d15ae9f7e49ed214d9e283df165f564f9410be8aa

test:
  secret_key_base: 22ddc17bc50fe8b722f2bca67639aa8e555433b6d5580c976f61b8b5902af637e90a1d7c1e6096575085d51fb003edb21eade517c1261877b424f15cd6abe925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
